events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    client_max_body_size 10m;

    upstream keycloak_up { server keycloak:8080; }
    upstream espacios_up { server ms-espacios:8081; }
    upstream vehiculos_up { server ms-vehiculos:8082; }
    upstream tickets_up  { server ms-tickets:8083; }
    upstream ia_up       { server ms-ia:8084; }
    upstream auth_up     { server ms-auth:8085; }

    server {
        listen 80;
        server_name localhost;

        location ~* \.(js|css)$ {
            root /usr/share/nginx/html;
            add_header Cache-Control "no-cache, must-revalidate";
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /realms/ {
            proxy_pass http://keycloak_up/realms/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port 80;
        }

        location /resources/ {
            proxy_pass http://keycloak_up/resources/;
        }

        location /api/auth {
            proxy_pass http://auth_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/admin {
            proxy_pass http://auth_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/perfil {
            proxy_pass http://auth_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/espacios {
            proxy_pass http://espacios_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/vehiculos {
            proxy_pass http://vehiculos_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/tickets {
            proxy_pass http://tickets_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ia {
            proxy_pass http://ia_up;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 10s;
            proxy_send_timeout 180s;
            proxy_read_timeout 180s;
        }
    }
}
